### ISSUE TITLE
CORS Issue with the Assets

### ISSUE THREAD

**Issue by Chalghouma** [BabylonJS/Assets#28]
I'm not sure if this is the right place to report this, but i'm getting CORS issues whether it be from the playground, or from any side-app that uses Babylon.JS
![image](https://user-images.githubusercontent.com/17048203/108073530-28ccfe00-7036-11eb-90d0-61e366c17035.png)

**Comment by RaananW** [comment]
CORS are being enabled, will take a few minutes. Thanks!

**Comment by Chalghouma** [comment]
That was fast, thank you @RaananW !
