### ISSUE TITLE
Invalid assets

### ISSUE THREAD

**Issue by vpenades** [BabylonJS/Assets#29]
These assets report errors with glTF validator:

    Elf/Elf.gltf
    meshes/Yeti/MayaExport
    meshes/Demos/retargeting/riggedMesh.glb

I'm using these files for unit testing, which I think it's the purpose of this repository... I would like these to be fixed, or moved to a separate directory for "malformed files", or removed altogether.

**Comment by PatrickRyanMS** [comment]
I will update the Yeti model, as this is a very old model. However, I don't have the source for the Elf.glTF or the riggedMesh.glb as neither was created in-house. We cannot move them as there are playgrounds which could reference them and are immutable so would break. But I would also say that our assets library is for assets for demos, not for unit testing so I would not rely on this repo for unit testing.
