### ISSUE TITLE
Request for clarification in README on scope of repo

### ISSUE THREAD

**Issue by AJamesPhillips** [BabylonJS/Assets#4]
Hi team,

Is this repo meant to stay only focused on Bablyon.js assets used on the site or could it grow much larger and incorporate community generated content.  Please see this [thread](https://forum.babylonjs.com/t/assets-store-similar-to-unity/3085/17?u=ajp) on the forum.  In particularly I'm looking for a replacement for [these unity assets](https://github.com/TheWorldSim/world-sim/issues/9) and if I can not find them I will at some point write my own... I would like for them to be useful for others hence asking about the scope for this repo.

Thank you,
ajp

**Comment by deltakosh** [comment]
Unfortunately we do not want to open it to be a general store as we cannot ensure compliance and trademarks

**Comment by deltakosh** [comment]
I clarified the reader. Thanks!

**Comment by AJamesPhillips** [comment]
Thank you!
