### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by andres-lowrie** [BabylonJS/Assets#5]
would be useful to have license information

**Comment by sebavan** [comment]
@RaananW and @PirateJC ???

**Comment by RaananW** [comment]
@PirateJC - I believe we can add a CC NC license? something like this one - https://creativecommons.org/licenses/by-nc/3.0/
@PatrickRyanMS - would be great to have your input on that as well

**Comment by PirateJC** [comment]
Yup that CC makes perfect sense to me!

Let's get @PatrickRyanMS's input as well

**Comment by PatrickRyanMS** [comment]
I thought we would be making them CC-BY 4.0 rather than CC-BY-ND 3.0. Do we care, in the spirit of open source, if anyone uses the assets repo for commercial use?

**Comment by sebavan** [comment]
The most permissive the better I agree :-) I wish there would be a license where ppl can do whatever as long as they say hello on the forum :-)

**Comment by RaananW** [comment]
CC-BY 4.0 it is! i'll add the license to the repo.

For future reference - if anyone is adding their assets to this repository they must agree to the license as well.
